[project]
name = "07-translate-ssyk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "pathlib>=1.0.1",
]
